### ISSUE TITLE
Remove gap between landing page and About Us section

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#14]
![image](https://user-images.githubusercontent.com/76390998/205638604-c9d8c185-7b7f-47b7-abf8-6568de7b3a54.png)

**Comment by Sk05062003** [comment]
Follow the Figma design: 
https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=oMHf7Ofr1fKpQu3R-3

**Comment by sankooru14** [comment]
@Sk05062003 can you assign this issue?

**Comment by sankooru14** [comment]
![image](https://user-images.githubusercontent.com/96348474/205641544-f906a9c0-394a-4bfa-8881-02414a121b5e.png)
@Sk05062003 I raised a pr
Can you check  it

**Comment by Sk05062003** [comment]
Please create PR to the dev branch.

**Comment by sankooru14** [comment]
@Sk05062003 I created pr to the dev branch
![image](https://user-images.githubusercontent.com/96348474/205643184-8885ac3d-9bf3-4ef1-bb16-e32b6e34bbbc.png)
