### ISSUE TITLE
Update UI of footer 

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#19]
![image](https://user-images.githubusercontent.com/76390998/205711560-47412860-845b-4f24-bc39-ebfd06ca3430.png)
Follow the Figma link: https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=c9bLcRQ9od9TV7th-3 to update the UI of the footer of the website. 

Note:-
1. Social Media Icon must be updated
2. Font family must be updated

**Comment by sankooru14** [comment]
@Sk05062003 can you assign this to me?

**Comment by Sparsh752** [comment]
@Sk05062003 Can you assign me this?

**Comment by sankooru14** [comment]
![image](https://user-images.githubusercontent.com/96348474/205820593-8d684f82-8b64-4873-b521-9ee793b7537c.png)
@Sk05062003 shall I raise pr?

**Comment by Sk05062003** [comment]
Please put in the names of five contributors (SONALI, AMISHA KUMARI, SHIVANI, VARUN THANNEERU, TEJAS TUPKE) instead of the dummy text "FULL NAME X"
Raise PR to the dev branch

**Comment by sankooru14** [comment]
![image](https://user-images.githubusercontent.com/96348474/205824155-7d5eb0e9-2edd-47c6-b316-1c7d8b4cda80.png)
@Sk05062003 why it is showing like this?

**Comment by Sk05062003** [comment]
Push to the dev branch of the forked repository and then create PR. 
'origin' has the url SK05062003/APClubIITP set to it.
Step1. Create a fork of this repository
Step2. git remote set-url origin https://github.com/YourUsername/APClubIITP

**Comment by sankooru14** [comment]
@Sk05062003 now can you check my pr?
