### ISSUE TITLE
Implement UI of the Magazine Section (Only two forms and not the Magazine Feedback)

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#20]
![image](https://user-images.githubusercontent.com/76390998/205712763-d97a0765-d9c6-4426-87ac-4555dc2dc19b.png)
Implement the UI of the magazine section using the Figma design: https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=c9bLcRQ9od9TV7th-3

Note:-
1. Make sure that two forms must be created (one for subscription and another for submitting feedback).
2. The Magazine Feedback section is created as a separate issue

**Comment by Sparsh752** [comment]
@Sk05062003 Can you assign me this?

**Comment by sankooru14** [comment]
@Sk05062003 I would like to work on this issue.
Can you assign this to me?

**Comment by sankooru14** [comment]
![image](https://user-images.githubusercontent.com/96348474/205850357-eb1713bd-2900-48cd-ad15-84757fb5a973.png)
@Sk05062003 Shall i raise pr?

**Comment by Sk05062003** [comment]
> ![image](https://user-images.githubusercontent.com/96348474/205850357-eb1713bd-2900-48cd-ad15-84757fb5a973.png) @Sk05062003 Shall i raise pr?

Yes. Raise a pr to dev branch

**Comment by sankooru14** [comment]
@Sk05062003 Can you check my pr?
