### ISSUE TITLE
Implement UI for the "Rolling" Magazine Feedback section

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#21]
![Screenshot (168)](https://user-images.githubusercontent.com/76390998/205714598-3410d5d8-a762-4df9-bb42-73db08c08c80.png)

Implement the UI of the magazine feedback section according to the Figma Design: https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=c9bLcRQ9od9TV7th-3

Note:-
1. The feedbacks keep rolling vertically, when not on-hover.
2. When the field is hovered to, then the list is scrollable.

**Comment by Sparsh752** [comment]
@Sk05062003 Can you assig me this?

**Comment by Sparsh752** [comment]
@Sk05062003 I have almost completed the issue, can you give me some bonus points, please?

**Comment by Sparsh752** [comment]
https://user-images.githubusercontent.com/94468600/205868350-540c4209-cc86-4402-a794-511eb1a96ef0.mov

Is this fine? should I pr?

**Comment by Sk05062003** [comment]
> @Sk05062003 I have almost completed the issue, can you give me some bonus points, please?

Hey C'mon
Codepeak people won't allow such requests. 

> Screen.Recording.2022-12-06.at.14.37.04.mov 
> Is this fine? should I pr?

Just a small change, the feedback should not roll once you hover over it. It should just become a scrollable division.

**Comment by Sparsh752** [comment]
@Sk05062003 ok

**Comment by Sparsh752** [comment]
@Sk05062003 The person who made the form has messed up a little bit

**Comment by Sk05062003** [comment]
> @Sk05062003 The person who made the form has messed up a little bit

Well, in that case, can you please be more particular about what the issue is?

**Comment by Sparsh752** [comment]
https://user-images.githubusercontent.com/94468600/205882836-6100671e-f342-431d-bc6d-b771fabfa141.mov

I have done the hover part. Also made the form and scrollable feedback form inline. I don't know why the height and width of form is small.

**Comment by Sparsh752** [comment]
@Sk05062003 Can I pr?

**Comment by Sparsh752** [comment]
@Sk05062003 I have pulled request

**Comment by Sk05062003** [comment]
> @Sk05062003 I have pulled request

![image](https://user-images.githubusercontent.com/76390998/205918823-76e223f4-a65a-4616-991e-ef14a0d41b44.png)
Content overflows and the orinigal content size is hindered.
Please resolve the issue and create PR again.

**Comment by Sparsh752** [comment]
@Sk05062003 fixed the overflow
