### ISSUE TITLE
Make the page responsive

### ISSUE THREAD

**Issue by Dibyendu303** [Sk05062003/APClubIITP#30]
The page is not responsive. Certain sections such as header section, events section and footer do not resize appropriately when viewed on a mobile screen. Can I work on this issue ?

**Comment by Sk05062003** [comment]
Sure. Go ahead!
I am assigning you this issue.

**Comment by Dibyendu303** [comment]
Hey, @Sk05062003 I submitted a PR request #39 . Please check
