### ISSUE TITLE
Add background to the Team section and team member cards

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#31]
Follow the Figma design: https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=MZlbXr3X8aTwVyvN-3
and add a background image to the Team section. Also, add the background colour to the team member cards(consider opacity) and border-radius.

**Comment by devika-singh** [comment]
@Sk05062003 Pls assign me this issue
