### ISSUE TITLE
Add Gallery and Blogs button on the landing page

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#32]
Follow Figma design: https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=MZlbXr3X8aTwVyvN-3

Note:-
1. The buttons should take to "gallery.html" and "blogs.html" which contain the navbar, footer(same as index.html), background colour and a heading.

**Comment by Sparsh752** [comment]
@Sk05062003 Can I work on this?

**Comment by Dibyendu303** [comment]
Please assign it to me @Sk05062003

**Comment by Dibyendu303** [comment]
Submitted a PR #39 in which I added these buttons
