### ISSUE TITLE
Reduce the height of footer to not more than 400px

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#34]
Follow the Figma design: https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=MZlbXr3X8aTwVyvN-3

If required, you can reduce the gap between lines, padding and margins.

Note: 
1. All the size reductions must be uniform over the footer
2. You are free to reduce the text size(uniformly for the whole footer), if required.

**Comment by Sparsh752** [comment]
@Sk05062003 Can I work on this?

**Comment by devika-singh** [comment]
@Sk05062003 can I work on this?

**Comment by ghost** [comment]
assign this to me

**Comment by Sk05062003** [comment]
> assign this to me

Issue is not fixed. No points will be awarded to you.
![image](https://user-images.githubusercontent.com/76390998/206851180-79044a79-41bb-4398-a301-d711d4eb894e.png)

**Comment by devika-singh** [comment]
@Sk05062003 added a pull request for this issue pls review it
