### ISSUE TITLE
Add Subcoord names and linkedIn IDs in the team section

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#36]
Follow the Figma design: 
https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=LSWcJ9dJ1Fney6Sm-3

Find the names and LinkedIn IDs of the subcoordinators here,
https://docs.google.com/document/d/1edW8HDoylnBdMtWaDwMKsdHXm4HHZqMes6uEXOPlHpQ/edit?usp=sharing

**Comment by Sparsh752** [comment]
@Sk05062003 Can I work on this?

**Comment by Sparsh752** [comment]
@Sk05062003 I have PR

**Comment by Sk05062003** [comment]
Please update the icon as per the Figma design.
And for Subcoords' linkedIn icon is not aligned vertically.
