### ISSUE TITLE
Related to issue #31, update the card for team members as per the UI design

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#41]
Follow the figma design:
https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=qgBB3eXVius3IHDU-3

Note:
1. Make a single card for team members instead of four cards.
2. Update the colors of the team section as per the figma design

**Comment by devika-singh** [comment]
@Sk05062003 Pls assign me this issue

**Comment by Sk05062003** [comment]
The issue is not resolved yet
![image](https://user-images.githubusercontent.com/76390998/206860797-6f6397f7-a996-4633-a3e0-fc10336d0610.png)

**Comment by devika-singh** [comment]
?? I'll rework

**Comment by devika-singh** [comment]
Ah the new addition since the pull request caused it
![image](https://user-images.githubusercontent.com/95178561/206861091-334d65f9-613a-4571-8fbc-b533115ce9af.png)
there is this piece of code in the HTML that causes the trouble I had commented it out since in figma file there are only four cards, 

Do I reopen a pull request with the commented code?

**Comment by devika-singh** [comment]
![image](https://user-images.githubusercontent.com/95178561/206861167-76078f9a-39f5-4df4-9e42-972fdf95e559.png)
works after commenting

**Comment by Sk05062003** [comment]
Oh, I see. Got missed out while resolving merge conflicts.

**Comment by Sk05062003** [comment]
LinkedIn Icons do not match the one in the Figma design and the card for the coordinator needs border-radius adjustment.
Please make these changes.

**Comment by devika-singh** [comment]
I have changed to these ones, Pls check if ok
![image](https://user-images.githubusercontent.com/95178561/206862245-037c91fa-e65b-443b-aae7-50901d8042ad.png)
![image](https://user-images.githubusercontent.com/95178561/206862465-0469c536-7a07-465e-b9f6-248a71711f26.png)
Added border to this too, all 29px like in figma

**Comment by devika-singh** [comment]
Added new Pul Request  https://github.com/Sk05062003/APClubIITP/pull/49
