### ISSUE TITLE
Related to issue #30, in the responsive branch, fix the Team section

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#42]
Follow the figma design:
https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=qgBB3eXVius3IHDU-3

Fix the team section
Pull the responsive branch of the forked repository into your local, commit changes and raise PR to the responsive branch only

**Comment by devika-singh** [comment]
@Sk05062003 Pls assign me this issue

**Comment by Sk05062003** [comment]
> @Sk05062003 Pls assign me this issue

You already have one issue assigned to you in this repository, so can't be assigned to you at the moment.

**Comment by Sk05062003** [comment]
> @Sk05062003 Pls assign me this issue

Will be assigned probably once issue #41 is resolved

**Comment by ghost** [comment]
assign this to me @Sk05062003

**Comment by Sk05062003** [comment]
> assign this to me @Sk05062003

You are already assigned one issue in this repository.

**Comment by Dibyendu303** [comment]
Please assign me @Sk05062003

**Comment by Sk05062003** [comment]
> Please assign me @Sk05062003

Make sure you pull the latest changes from base:dev into the fork:responsive and to your local, resolve merge issues and then raise PR to responsive of base repository

**Comment by Dibyendu303** [comment]
Okay

**Comment by Dibyendu303** [comment]
@Sk05062003 Submitted a PR #46 . Please review.

**Comment by Sk05062003** [comment]
![image](https://user-images.githubusercontent.com/76390998/206850962-542a3818-425a-4f54-be71-4cddb6effbf0.png)
The logo size needs to be reduced 
![Screenshot (177)](https://user-images.githubusercontent.com/76390998/206850997-fa0cd660-fb08-4542-810f-786d1f92b688.png)
Subcoords for each committee must be under the coords

**Comment by Sk05062003** [comment]
> @Sk05062003 Submitted a PR #46 . Please review.

Please fix issues and raise PR.

**Comment by Dibyendu303** [comment]
@Sk05062003 Please check PR #48
