### ISSUE TITLE
Remove horizontal scroll bar

### ISSUE THREAD

**Issue by Sparsh752** [Sk05062003/APClubIITP#45]
<img width="1440" alt="Screenshot 2022-12-09 at 21 46 10" src="https://user-images.githubusercontent.com/94468600/206745367-0353a94b-266c-4b9f-93c2-2fa1f75a38f0.png">

There is horizontal scrollbar which needs to be removed above magazine section

**Comment by Dibyendu303** [comment]
@Sparsh752 I have removed it while I was fixing the Teams section
