### ISSUE TITLE
Implement "Astronomical Calendar Collapsible Carousel" 

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#5]
Follow the Figma design https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=217%3A2&t=Z5LzI5Ao21Y8MWBN-0 to implement astronomical calendar collapsible carousel using javascript. 

Things to note:-
1. Section should be collapsible
2. Dummy content should be put up as shown in the Figma design and the dummy content should be fetched from a JSON file(with objects of former 
{
   date : "<Date>",
   title: "Lorem Ipsum",
   description: "Lorem ipsum dolor sit ..."
}
)
3. The Left and Right arrow keys of the carousel to switch between different astronomical events should change the year also(when required)

**Comment by sidling1** [comment]
Can you assign me this?

**Comment by sankooru14** [comment]
@Sk05062003 I would like to work on this.
can you assign this issue to me?

**Comment by Sparsh752** [comment]
@Sk05062003 Can you assign this to me?

**Comment by nik132-eng** [comment]
If this problem isn't resolved, I'd like to get involved. can you assign me this issue?

**Comment by shashank4628** [comment]
Can you assign me this issue or any other issue??

**Comment by AdityaPaul03** [comment]
Can this issue be assigned..... I'd like to be involved

**Comment by AdityaPaul03** [comment]
@Sk05062003 I would like to contribute on this request. Kindly assign me this issue if possible.

**Comment by Dibyendu303** [comment]
@Sk05062003 If the issue is not resolved yet.. can I work on it. I can also make it responsive.

**Comment by Dibyendu303** [comment]
@Sk05062003 Submitted a PR #51
