### ISSUE TITLE
Add About section to the website 

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#6]
Refer to the Figma design
https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=302%3A176&t=Z5LzI5Ao21Y8MWBN-3
and for the content of the About section visit
https://drive.google.com/drive/folders/1mNq6Xpi8cO1pPZN15I3PVeC04xCBf6h1?usp=sharing

**Comment by Adittya-Gupta** [comment]
Hey! I think I can work on this issue. Please assign it to me

**Comment by AyushTripathiIITP** [comment]
I would like to work on this issue please assign this to me

**Comment by AyushTripathiIITP** [comment]
@Sk05062003

**Comment by sankooru14** [comment]
@Sk05062003 could you please  accept the request to access the figma file?

**Comment by thevermaashutosh** [comment]
Can I be assigned this task? @thevermaashutosh

**Comment by Sk05062003** [comment]
> @Sk05062003 could you please accept the request to access the figma file?

You can access it now at https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=ikWVrmeAgYw5bcWe-1

**Comment by sankooru14** [comment]
![image](https://user-images.githubusercontent.com/96348474/205567523-d7045989-496c-4abc-b192-51ab8d6863fc.png)
I have raised a pr
@Sk05062003 can you check it?

**Comment by sankooru14** [comment]
![image](https://user-images.githubusercontent.com/96348474/205567730-941cb322-4dc0-44d1-b2b7-38b7cfa62353.png)
@Sk05062003  I have raised a pr
Can you check it out?

**Comment by sankooru14** [comment]
![image](https://user-images.githubusercontent.com/96348474/205568816-2103664e-9653-4dbc-bd77-736a609149f7.png)
Here is the webpage after code implementation

**Comment by Sk05062003** [comment]
> ![image](https://user-images.githubusercontent.com/96348474/205568816-2103664e-9653-4dbc-bd77-736a609149f7.png) Here is the webpage after code implementation

I would like to mention that the issue has been assigned to @AyushTripathiIITP and your PR cannot be accepted as per the guidelines of Codepeak'22
