### ISSUE TITLE
Add Events Carousel

### ISSUE THREAD

**Issue by Sk05062003** [Sk05062003/APClubIITP#8]
Similar to issue #5, here a carousel has been implemented 
Figma Link: https://www.figma.com/file/kpeZYE7cCOnKOkaQU8iiEj/APClub?node-id=0%3A1&t=Z5LzI5Ao21Y8MWBN-0

Note:
1. The event displayed at the centre must be on focus
2. There is a horizontal scroll in the Events section and the scrollbar is hidden

**Comment by Adittya-Gupta** [comment]
Hey @Sk05062003  I can work on this issue!! Plz assign it to me
